# Generated by Django 4.2.2 on 2023-11-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_userupload_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userupload",
            name="image",
            field=models.ImageField(blank=True, upload_to="user_uploads\\"),
        ),
    ]
